language: java
jdk: oraclejdk8

notifications:
  email:
    recipients:
      - Mark.d.denner@gmail.com
    on_success: always
    on_failure: always
    
cache:
  directories:
    - $HOME/.m2

script:
  mvn verify
